[pytest]
filterwarnings =
    ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated:DeprecationWarning:dateutil\.tz\.tz
    ignore:Accessing argon2\.__version__ is deprecated:DeprecationWarning:passlib\.handlers\.argon2
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
