"""Fallback question generation service when LLM is unavailable or disabled."""

from __future__ import annotations

from typing import Any, Dict, List

from backend.app.services.question_template_service import QuestionTemplateService


class QuestionFallbackService:
    """Create robust local fallback candidates from lesson chunks."""

    def __init__(self) -> None:
        self.template_service = QuestionTemplateService()

    def build_candidates(
        self,
        *,
        lesson_title: str,
        chunks: List[Dict[str, Any]],
        target_count: int,
        question_types: List[str],
        difficulty: str,
        bloom_levels: List[str],
        retry_attempts: int = 2,
    ) -> List[Dict[str, Any]]:
        candidates: List[Dict[str, Any]] = []
        seen: set[str] = set()
        attempts = max(1, retry_attempts + 1)
        for attempt in range(attempts):
            if len(candidates) >= target_count:
                break
            retry_chunks = self._select_retry_chunks(chunks=chunks, attempt=attempt)
            retry_types = self._select_retry_types(
                question_types=question_types,
                attempt=attempt,
            )
            retry_bloom = self._select_retry_bloom_levels(
                bloom_levels=bloom_levels,
                attempt=attempt,
            )
            batch = self.template_service.build_candidates(
                lesson_title=lesson_title,
                chunks=retry_chunks,
                target_count=max(0, target_count * 2),
                question_types=retry_types,
                difficulty=difficulty,
                bloom_levels=retry_bloom,
                max_per_chunk=1,
            )
            for item in batch:
                signature = self._signature(item)
                if not signature or signature in seen:
                    continue
                seen.add(signature)
                candidates.append(item)
                if len(candidates) >= target_count:
                    break

        for item in candidates:
            metadata = item.get("metadata") if isinstance(item.get("metadata"), dict) else {}
            metadata["generation_mode"] = "local_fallback"
            metadata["generation_source"] = "local_fallback"
            metadata.setdefault(
                "reasoning_note",
                "Generated by local fallback due to unavailable or disabled LLM.",
            )
            item["metadata"] = metadata
        return candidates[: max(0, target_count)]

    @staticmethod
    def _signature(candidate: Dict[str, Any]) -> str:
        question = " ".join(str(candidate.get("question") or "").lower().split())
        answer = " ".join(str(candidate.get("correct_answer") or "").lower().split())
        return f"{question}|{answer}"

    @staticmethod
    def _select_retry_chunks(
        *,
        chunks: List[Dict[str, Any]],
        attempt: int,
    ) -> List[Dict[str, Any]]:
        if attempt <= 0:
            return list(chunks)
        if attempt % 2 == 1:
            return list(reversed(chunks))
        return [chunk for index, chunk in enumerate(chunks) if index % 2 == attempt % 2] or list(chunks)

    @staticmethod
    def _select_retry_types(*, question_types: List[str], attempt: int) -> List[str]:
        selected = question_types or ["multiple_choice"]
        if attempt == 0:
            return selected
        if attempt % 2 == 1:
            return ["multiple_choice", "short_answer", "true_false"]
        return ["short_answer", "multiple_choice", "true_false"]

    @staticmethod
    def _select_retry_bloom_levels(*, bloom_levels: List[str], attempt: int) -> List[str]:
        selected = bloom_levels or ["remember", "understand"]
        if attempt == 0:
            return selected
        if attempt % 2 == 1:
            return ["understand", "apply", "remember", "analyze"]
        return ["apply", "analyze", "understand", "remember"]


question_fallback_service = QuestionFallbackService()